# Generated by Django 2.1 on 2023-06-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230602_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionprediction',
            name='input_image',
        ),
        migrations.RemoveField(
            model_name='conditionprediction',
            name='output_image',
        ),
        migrations.AddField(
            model_name='conditionprediction',
            name='input_url',
            field=models.ImageField(default='default.jpg', upload_to='input_images'),
        ),
        migrations.AddField(
            model_name='conditionprediction',
            name='output_url',
            field=models.ImageField(default='default.jpg', upload_to='output_images'),
        ),
    ]
