# Generated by Django 2.1 on 2023-06-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230602_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummymodel',
            name='x_image',
            field=models.ImageField(default='default.jpg', upload_to='media/input_images/'),
        ),
        migrations.AlterField(
            model_name='dummymodel',
            name='x',
            field=models.IntegerField(default=0),
        ),
    ]
