# Generated by Django 2.1 on 2023-06-06 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20230604_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConditionPrediction',
            new_name='ImagePrediction',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Prediction',
        ),
    ]
