# Generated by Django 2.1 on 2023-06-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230606_0731'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageprediction',
            table='user_image_prediction',
        ),
    ]
