# Generated by Django 2.1 on 2023-06-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230606_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprediction',
            name='result',
            field=models.TextField(blank=True, default='In progress', null=True),
        ),
        migrations.AlterField(
            model_name='imageprediction',
            name='timestamp',
            field=models.DateTimeField(editable=False),
        ),
    ]
