# Generated by Django 2.1 on 2023-06-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230607_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageprediction',
            old_name='result',
            new_name='status',
        ),
    ]
