# Generated by Django 2.1 on 2023-06-12 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20230608_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(editable=False)),
                ('date_key', models.IntegerField(blank=True, default=None, null=True)),
                ('disease', models.CharField(max_length=100)),
                ('location_xyxy', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
                ('image_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ImagePrediction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_disease_prediction',
            },
        ),
    ]
