# Generated by Django 2.1 on 2023-06-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20230612_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseprediction',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
