# Generated by Django 2.1 on 2023-06-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230618_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio2',
        ),
    ]
